version: '3.8'

services:
  # Keycloak Authentication Service
  keycloak:
    image: quay.io/keycloak/keycloak:26.3
    container_name: atexo_keycloak
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 7080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
      KC_PROXY_HEADERS: "xforwarded"
      KC_PROXY_TRUSTED_ADDRESSES: "172.16.0.0/12,192.168.0.0/16,10.0.0.0/8"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7080/health/ready"]
      interval: 15s
      timeout: 2s
      retries: 15
    command: ["start-dev", "--http-port", "7080", "--https-port", "7443", "--import-realm"]
    ports:
      - "7080:7080"
      - "7443:7443"
    volumes:
       - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    networks:
      - atexo_chatbot
    restart: unless-stopped

  # Flask Backend - Add dependency on Keycloak
  flask-app:
    depends_on:
      - keycloak

  # HAProxy - Add dependency on Keycloak
  haproxy:
    depends_on:
      - keycloak
      - wren-ui
      - wren-ai-service
      - wren-engine
      - ibis-server
