version: '3.8'

services:
  haproxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: atexo_haproxy
    ports:
      - "3000:3000"  # WrenAI UI
      - "8000:8000"  # WrenAI AI Service
      - "8001:8001"  # WrenAI Engine
      - "8002:8002"  # WrenAI Ibis Server
      - "8404:8404"  # HAProxy stats page
    env_file:
      - env.example
    depends_on:
      - keycloak
    networks:
      - atexo_chatbot
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "haproxy", "-c", "-f", "/usr/local/etc/haproxy/haproxy.cfg"]
      interval: 30s
      timeout: 10s
      retries: 3

  keycloak:
    image: quay.io/keycloak/keycloak:26.3
    container_name: atexo_keycloak
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 7080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
      # Configure proxy headers as per Keycloak documentation
      KC_PROXY_HEADERS: "xforwarded"
      KC_PROXY_TRUSTED_ADDRESSES: "172.16.0.0/12,192.168.0.0/16,10.0.0.0/8"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7080/health/ready"]
      interval: 15s
      timeout: 2s
      retries: 15
    command: ["start-dev", "--http-port", "7080", "--https-port", "7443"]
    networks:
      - atexo_chatbot
    restart: unless-stopped

volumes:
  wrenai_data:

networks:
  atexo_chatbot:
    driver: bridge 